In [1]:
import pandas as pd
import numpy as np
import spacy
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split


In [2]:
# By default in CountVectorizer n_grams = 1
v = CountVectorizer()
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

{'thor': 5, 'hathodawala': 1, 'is': 2, 'looking': 4, 'for': 0, 'job': 3}

In [3]:
# CountVectorizer n_grams = 2
v = CountVectorizer(ngram_range=(2,2))
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

{'thor hathodawala': 4,
 'hathodawala is': 1,
 'is looking': 2,
 'looking for': 3,
 'for job': 0}

In [4]:
v = CountVectorizer(ngram_range=(1,2))
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

{'thor': 9,
 'hathodawala': 2,
 'is': 4,
 'looking': 7,
 'for': 0,
 'job': 6,
 'thor hathodawala': 10,
 'hathodawala is': 3,
 'is looking': 5,
 'looking for': 8,
 'for job': 1}

In [5]:
v = CountVectorizer(ngram_range=(1,3))
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

{'thor': 12,
 'hathodawala': 2,
 'is': 5,
 'looking': 9,
 'for': 0,
 'job': 8,
 'thor hathodawala': 13,
 'hathodawala is': 3,
 'is looking': 6,
 'looking for': 10,
 'for job': 1,
 'thor hathodawala is': 14,
 'hathodawala is looking': 4,
 'is looking for': 7,
 'looking for job': 11}

In [6]:
corpus = [
    "Thor ate pizza", 
    "Loki is tall", 
    "Loki is eating pizza"
]

nlp = spacy.load("en_core_web_sm")

def preprocess(text) :
    doc = nlp(text)

    filtred_tokens = []

    for token in doc : 
        if token.is_stop or token.is_punct :
            continue
        filtred_tokens.append(token.lemma_)

    return " ".join(filtred_tokens)

preprocess("Loki is eating pizza")

'Loki eat pizza'

In [7]:
corpus_preprocess  = [preprocess(text) for text in corpus]
corpus_preprocess

['thor eat pizza', 'Loki tall', 'Loki eat pizza']

In [8]:
v = CountVectorizer(ngram_range=(1,2))
v.fit(corpus_preprocess)
v.vocabulary_

{'thor': 7,
 'eat': 0,
 'pizza': 5,
 'thor eat': 8,
 'eat pizza': 1,
 'loki': 2,
 'tall': 6,
 'loki tall': 4,
 'loki eat': 3}

In [9]:
v.transform(["Thor eat pizza"]).toarray()

array([[1, 1, 0, 0, 0, 1, 0, 1, 1]], dtype=int64)

In [10]:
v.transform(["Hulk eat pizza"]).toarray()

array([[1, 1, 0, 0, 0, 1, 0, 0, 0]], dtype=int64)

# News Category Classification Problem


Here we want to do a news category classification. We will use bag of n-grams and traing a machine learning model that can categorize any news into one of the following categories, <br>

1- BUSINESS <br>
2- SPORTS <br>
3- CRIME <br>
4- SCIENCE <br>

- This data consists of two columns. - Text- Category
- Text is a news article
- Category can be one of these 4: 'BUSINESS', 'SPORTS', 'CRIME', 'SCIENCE', to keep things simple I trimmed additional categories from the original dataset

In [11]:
df = pd.read_json("news_dataset.json")
df.head()

text  category
0  Watching Schrödinger's Cat Die University of C...   SCIENCE
1     WATCH: Freaky Vortex Opens Up In Flooded Lake    SCIENCE
2  Entrepreneurs Today Don't Need a Big Budget to...  BUSINESS
3  These Roads Could Recharge Your Electric Car A...  BUSINESS
4  Civilian 'Guard' Fires Gun While 'Protecting' ...     CRIME

In [12]:
df.shape

(12695, 2)

In [13]:
df.category.value_counts() #to know if the dataset is balance or not

category
BUSINESS    4254
SPORTS      4167
CRIME       2893
SCIENCE     1381
Name: count, dtype: int64

In [14]:
#Handel class imbalance
min_samples = 1381

df_business = df[df.category=="BUSINESS"].sample(min_samples, random_state=2022)
df_sports = df[df.category=="SPORTS"].sample(min_samples, random_state=2022)
df_crime = df[df.category=="CRIME"].sample(min_samples, random_state=2022)
df_science = df[df.category=="SCIENCE"].sample(min_samples, random_state=2022)

In [15]:
df_balanced = pd.concat([df_business, df_sports, df_crime, df_science], axis=0)
df_balanced.category.value_counts()

category
BUSINESS    1381
SPORTS      1381
CRIME       1381
SCIENCE     1381
Name: count, dtype: int64

In [16]:
df_balanced['category_num'] = df_balanced.category.map({
    'BUSINESS' : 0,
    'SPORTS' : 1,
    'CRIME' : 2,
    'SCIENCE' : 3
})

In [17]:
X_train, X_test, y_train, y_test = train_test_split(
    df_balanced.text, 
    df_balanced.category_num, 
    test_size=0.2,
    random_state=2022,
    stratify=df_balanced.category_num )

In [18]:
y_train.value_counts()

category_num
3    1105
2    1105
0    1105
1    1104
Name: count, dtype: int64

In [19]:
y_test.value_counts()

category_num
1    277
0    276
3    276
2    276
Name: count, dtype: int64

# Build a Bag of words Model

In [20]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

clf = Pipeline([
    ('vectorizer_bow' , CountVectorizer()),
    ('Multi NB' , MultinomialNB())
])

clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.75      0.87      0.81       276
           1       0.93      0.80      0.86       277
           2       0.83      0.90      0.86       276
           3       0.90      0.80      0.85       276

    accuracy                           0.84      1105
   macro avg       0.85      0.84      0.84      1105
weighted avg       0.85      0.84      0.84      1105



In [21]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

clf = Pipeline([
    ('vectorizer_bow' , CountVectorizer(ngram_range=(1,2))),
    ('Multi NB' , MultinomialNB())
])

clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.69      0.90      0.78       276
           1       0.95      0.74      0.83       277
           2       0.82      0.88      0.85       276
           3       0.92      0.78      0.84       276

    accuracy                           0.82      1105
   macro avg       0.85      0.82      0.83      1105
weighted avg       0.85      0.82      0.83      1105



In [22]:
X_test[:5]

3716     African Nation Slaps Exxon With Fine Nearly 7 ...
608      These Cringe-Worthy Stories Show It Can Be Har...
11172    LISTEN: The Accidental Discovery That Proved T...
1346     Build Loyalty -- The Cost -- $00.00 Remember y...
1356     Man Killed By Michigan Police Wasn't Targeting...
Name: text, dtype: object

In [23]:
y_test[:5]

3716     0
608      3
11172    3
1346     0
1356     2
Name: category_num, dtype: int64

In [24]:
y_pred[:5]

array([0, 0, 3, 0, 2], dtype=int64)

In [25]:
df_balanced

text  category  \
11967  GCC Business Leaders Remain Confident in the F...  BUSINESS   
2912   From the Other Side; an Honest Review from Emp...  BUSINESS   
3408   Mike McDerment, CEO of FreshBooks, Talks About...  BUSINESS   
502    How to Market Your Business While Traveling th...  BUSINESS   
5279   How to Leverage Intuition in Decision-making I...  BUSINESS   
...                                                  ...       ...   
2178   Aquarium To Monitor Animals' Behavior Changes ...   SCIENCE   
5682   How Google Glass Could Save Lives In The Hospi...   SCIENCE   
1643   Honda's Gravity Modification Research For us A...   SCIENCE   
11428  EVERYONE Loves Alternative Facts THE POWER OF ...   SCIENCE   
8101   From Cooking to Conservation: Women Take Actio...   SCIENCE   

       category_num  
11967             0  
2912              0  
3408              0  
502               0  
5279              0  
...             ...  
2178              3  
5682              3  
1643              3  
11428             3  
8101              3  

[5524 rows x 3 columns]

In [28]:
# The usage of preprocessing
# Create a preproces for text column
df_balanced['preprocessed_txt'] = df_balanced['text'].apply(preprocess) 

In [29]:
df_balanced.head()

text  category  \
11967  GCC Business Leaders Remain Confident in the F...  BUSINESS   
2912   From the Other Side; an Honest Review from Emp...  BUSINESS   
3408   Mike McDerment, CEO of FreshBooks, Talks About...  BUSINESS   
502    How to Market Your Business While Traveling th...  BUSINESS   
5279   How to Leverage Intuition in Decision-making I...  BUSINESS   

       category_num                                  preprocessed_text  \
11967             0  GCC Business Leaders remain Confident Face Reg...   
2912              0  Honest Review employee wake morning love impor...   
3408              0  Mike McDerment ceo FreshBooks Talks give build...   
502               0  market business travel World recently amazing ...   
5279              0  Leverage intuition decision making feel safe r...   

                                        preprocessed_txt  
11967  GCC Business Leaders remain Confident Face Reg...  
2912   Honest Review employee wake morning love impor...  
3408   Mike McDerment ceo FreshBooks Talks give build...  
502    market business travel World recently amazing ...  
5279   Leverage intuition decision making feel safe r...

# Build a model with pre processed text

In [30]:
X_train, X_test, y_train, y_test = train_test_split(
    df_balanced.preprocessed_text, 
    df_balanced.category_num, 
    test_size=0.2,
    random_state=2022,
    stratify=df_balanced.category_num )

In [31]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

clf = Pipeline([
    ('vectorizer_bow' , CountVectorizer(ngram_range=(1,2))),
    ('Multi NB' , MultinomialNB())
])

clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.88      0.84       276
           1       0.92      0.82      0.87       277
           2       0.83      0.92      0.87       276
           3       0.90      0.81      0.85       276

    accuracy                           0.86      1105
   macro avg       0.86      0.86      0.86      1105
weighted avg       0.86      0.86      0.86      1105



If you compare above classification report for (1,2) gram with the one from unprocessed text, you will find some improvement in the model that uses preprocessed cleaned up text. Hence we can conclude that for this particular problem using preprocessing (removing stop words, lemmatization) is improving the performance of the model

#### Plot confusion matrix



In [32]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[243,   8,  17,   8],
       [ 10, 228,  29,  10],
       [ 15,   2, 253,   6],
       [ 36,   9,   7, 224]], dtype=int64)